project:
  type: website
  output-dir: docs

bibliography: references.bib
  
website:
  title: "Çizgeler"
  site-url: https://cizgeler.github.io/
  repo-url: "https://github.com/cizgeler/cizgeler.github.io"
  description: "Matematiğin türlü durumları için animasyonlar..."
  favicon: style/cizgeler.png
  twitter-card: true
  open-graph: true
  back-to-top-navigation: true
  
  navbar:
    background: "#A7D5E8"
    logo: "style/cizgeler.png"
    align: center
    pinned: true
    left:
      - text: "Matematiğin türlü durumları için animasyonlar..."
        file: about.qmd
    right:
      - about.qmd
      - icon: youtube
        href: https://www.youtube.com/@cizgeler
      - icon: github
        href: https://github.com/cizgeler
      - icon: rss
        href: index.xml
  
  page-footer:
    background: "#A7D5E8"
    left:
      - href: https://www.quarto.org
        text: "Burası Quarto ile oluşturulmuştur."
    right:
      - href: https://creativecommons.org/licenses/by-sa/4.0/deed.tr
        text: "CC BY-SA 4.0" 
        
 
##comments:
    #giscus: 
      #repo: cizgeler/cizgeler.github.io
      #repo-id: R_kgDOINSXzA
      #category: Announcements
      #category-id: DIC_kwDOINSXzM4CR9ea
      #mapping: url
      #reactions-enabled: true
      #input-position: bottom
      #theme: light_tritanopia
      #language: tr 
      
google-analytics: "G-HBBE52PLTN"
  
format:
  html:
    theme:
      light: [cosmo, style/dsbox.scss]
      dark: [cosmo, style/dsbox.scss, style/dark.scss]
    toc: true
    date-format: "DD/MM/YYYY"
    lang: tr
    language: 
      toc-title-document: "İçindekiler"
      back-to-top: "Başa dön"
      callout-tip-title: "İpucu"
      listing-page-field-categories: "Konular"
    include-in-header: style/preamble.html   
    mainfont: "Atkinson Hyperlegible"
    
editor: visual

execute:
  freeze: auto


